package com.example.kotlinmusic.model

data class MusicModel (
    var wrapperType: String? = null,
    var kind: String? = null,
    var collectionId: Int? = 0,
    var trackId: Int? = 0,
    var artistName: String? = null,
    var collectionName: String? = null,
    var trackName: String? = null,
    var collectionCensoredName: String? = null,
    var trackCensoredName: String? = null,
    var collectionArtistId: Int? = 0,
    var collectionArtistViewUrl: String? = null,
    var collectionViewUrl: String? = null,
    var trackViewUrl: String? = null,
    var previewUrl: String? = null,
    var artworkUrl30: String? = null,
    var artworkUrl60: String? = null,
    var artworkUrl100: String? = null,
    var collectionPrice: Double? = 0.0,
    var trackPrice: Double? = 0.0,
    var collectionHdPrice: Double? = 0.0,
    var trackHdPrice: Double? = 0.0,
    var releaseDate: String? = null,
    var collectionExplicitness: String? = null,
    var trackExplicitness: String? = null,
    var discCount: Int? = 0,
    var trackCount: Int? = 0,
    var trackNumber: Int? = 0,
    var trackTimeMillis: Int? = 0,
    var country: String? = null,
    var currency: String? = null,
    var primaryGenreName: String? = null,
    var contentAdvisoryRating: String? = null,
    var longDescription: String? = null,
    var hasITunesExtras: Boolean? = false,
    var trackRentalPrice: Double? = 0.0,
    var trackHdRentalPrice: Double? = 0.0,
    var artistId: Int? = 0,
    var artistViewUrl: String? = null,
    var shortDescription: String? = null,
    var description: String? = null,
    var amgArtistId: Int? = 0,
    var copyright: String? = null,
    var isStreamable: Boolean? = false,
    var collectionArtistName: String? = null
)